-- Production note:
-- Do not store default users or password hashes in source control.
-- Create the first administrator through /setup with APP_SETUP_ENABLED=1,
-- then set APP_SETUP_ENABLED=0 again in the hosting environment.
